appId: com.github.biltudas1.sequence
---
- launchApp:
    clearState: true
- tapOn: "Sign in with Google"
- assertVisible: "Please configure server settings first"
- tapOn: "Server Configuration"
- tapOn: "Server Endpoint"
- inputText: "${MAESTRO_SEQUENCE_SERVER_URI}"
- tapOn: "Test Connection"
- assertVisible: (?i)server.+compatible?.+
- tapOn: "Save"
