services:
  sequence:
    image: ghcr.io/biltudas1/sequence:latest
    container_name: sequence-server
    ports:
      - "8888:8888"
    volumes:
      - sequence_data:/data
    read_only: true
    restart: unless-stopped

volumes:
  sequence_data:
